RemoteIDModule/BLE_TX.cpp
RemoteIDModule/BLE_TX.h
RemoteIDModule/CANDriver.cpp
RemoteIDModule/CANDriver.h
RemoteIDModule/DroneCAN.cpp
RemoteIDModule/RemoteIDModule.ino
RemoteIDModule/WiFi_TX.cpp
RemoteIDModule/options.h

Existing BLE code did work, but was not compliant:
- BLE legacy was not configured correctly, likely regular BLE 5 was used
- BLE Long Range, also the primary channels needs to be set to coded
- Reduced the update rate to the compliant update rate. A higher transmission rate will lead to more power consumption and may increase interference to other radio modules.

fix ble transmission protocols

---

RemoteIDModule/BLE_TX.cpp
RemoteIDModule/BLE_TX.h
RemoteIDModule/WiFi_TX.cpp
RemoteIDModule/WiFi_TX.h
RemoteIDModule/transmitter.cpp
RemoteIDModule/transmitter.h

- existing code was transmitting NAN packets on channel 1. This should be channel 6 for NAN packets. Both verified with a wireshark capture
- changed the device MAC address to a local generated MAC address. This would have two benefits a) you can't track a transponder based on the MAC address b) related, typically the original MAC address is considered to be a privacy sensitive information element. So, using the original MAC address may cause issues with existing privacy laws (if you capture them by receivers). Using a local generated MAC address at every boot of the transmitter solves this.

WiFi NAN, bug fix transmit on channel 6, set to random MAC address

---

README.md

- Bluemark model names had a small typo. (It is dbxxx, where db stands for **D**rone**B**eacon.)
- Added links to the product page and also a direct link to buy the module.
- Also added to the word "legacy" to the db110 model as typically most interested users want the db200 module.

bluemark info: fix typo in model name + added links for product info and buying

---

RemoteIDModule/board_config.h

The termination resistors can be enabled by GPIO 10. Existing code had a typo.

db200: typo, termination resistors are GPIO 10

---

RemoteIDModule/options.h

Disable WiFi NAN transmission by default.
Most users only need BLE legacy + BLE Long Range mode.

disable WiFi NaN transmission by default

---

RemoteIDModule/board_config.h

similar to the DB200 firmware, this patch enables the status LED for the DB110 module.

enable status LED for BlueMark DB110 module

---

BUILDING.md
RemoteIDModule/mavlink.cpp
scripts/install_build_env.sh

And update the build dependencies.
For some reason, installing python3 pyserial was good enough for me to get the compile process completed but not enough for the upload part. I needed also python pyserial for that. It could just be my old Ubuntu installation, which has gotten messed up over time so I only added a comment about the latter to the build instructions.
BTW: I have also noticed that `make setup` will fail if you are behind a proxy server (not surprisingly since it is trying to download a bunch of things). What surprised me was that also the pure `make` will occasionally fail (I don't know why that wants to access the internet). This is probably something inside the Arduino tools. I didn't try to start fighting with this but turned off the VPN on my home machine (wouldn't be an …

Set heartbeat autopilot correctly

---

RemoteIDModule/Makefile
RemoteIDModule/RemoteIDModule.ino
RemoteIDModule/board_config.h

- adds LED_MODE_FLASH as an alternative to the default basic LED behavior. 
- adds JW_TBD placeholder for Jeff Wurzbach module board
Note - @tridge  this adds two bools that indicate PFST and ARM Check status. The PFST currently gets set on after the inits() are run on the transmitters, however we'll want to more explicitly set this variable if we can.

Added Flashing LED Mode and JW Board Placeholder

---

RemoteIDModule/web/index.html

- disable/hide progress text when the page loads
- generates a popup after firmware upgrade has finished

improved firmware update via web interface

---

RemoteIDModule/DroneCAN.cpp
RemoteIDModule/mavlink.cpp
RemoteIDModule/transport.cpp
RemoteIDModule/transport.h

Check the timestamp of the system and location messages. Only update the last_*_ms value if the newly received packet has a different timestamp. 
This should cover situations in which the flight controller keeps sending packets with the same information. Because it crashed? The current arm_status_check function won't detect such cases.

only update last received packet timestamp of system/location messages if the timestamp inside the packets are updated

---

scripts/install_build_env.sh

I ran "make boards" and got the following message.
I change the version of arduino-cli from 0.26.0 to 0.27.1.
messages:
A new release of Arduino CLI is available: 0.26.0 → 0.27.1
https://arduino.github.io/arduino-cli/latest/installation/#latest-packages

scripts: Bring arduino-cli version up to date

---

RemoteIDModule/status.cpp

In TABLE 7 of F3411-22A, UNKNOWN, if latitude and longitude are 0.
I want to show UNKNOWN, when latitude and longitude are 0.
AFTER
CASE1
CASE2
BEFORE

location: Set to UNKNOWN when latitude and longitude are 0

---

RemoteIDModule/Makefile
RemoteIDModule/board_config.h

ESP32-C3 based ArduRemoteID board from mRobotics

Add support for mRo RemoteID M10049 board

---

scripts/install_build_env.sh

While following the linux build directions in `BUILD.md`, the script `scripts/regen_headers.sh` fails to generate DroneCAN headers due to a missing python module:
```
Generating DroneCAN headers for libcanard
Traceback (most recent call last):
File "/flash/arduremoteid/modules/dronecan_dsdlc/dronecan_dsdlc.py", line 20, in <module>
from dronecan_dsdlc_tester import *
File "/flash/arduremoteid/modules/dronecan_dsdlc/dronecan_dsdlc_tester.py", line 12, in <module>
import pexpect
ModuleNotFoundError: No module named 'pexpect'
./scripts/regen_headers.sh: line 16: cd: libraries/DroneCAN_generated: No such file or directory
./scripts/regen_headers.sh: line 16: cd: libraries/DroneCAN_generated: No such file or directory
./scripts/regen_headers.sh: line 16: cd: libraries/DroneCAN_generated: No …
```

fix: Install `pexpect` to fix failing `regen_headers.sh`

---

RemoteIDModule/BLE_TX.cpp
RemoteIDModule/BLE_TX.h
RemoteIDModule/RemoteIDModule.ino

In the current implementation, BLE4 legacy transmission work for about 30 seconds. Then it crashes and no BT4 legacy packets can be received anymore. 
The "issue" seems to be caused the separate BLE legacy advertisement service for the BLE device name. This was also solved in this PR https://github.com/ArduPilot/ArduRemoteID/pull/26 but due to parallel code development at that time, this part wasn't included. The solution is to incorporate the BLE device name broadcast into the regular BT4 transmissions. Not sure what the underlying issue is, perhaps it is just a bug in the ESP/Arduino environment.

bugfix BLE legacy advertisements broken

---

RemoteIDModule/BLE_TX.cpp

Due to the merging of the dual ID functionality and including the BLE name as one of the BT4 packets in 1.11, the advertisement interval of BT4 transmissions has to be decreased accordingly. Otherwise some BT4 packets may not be broadcast at all.

Ble legacy transmission rate fix

---

RemoteIDModule/check_firmware.cpp
RemoteIDModule/check_firmware.h
RemoteIDModule/web/index.html
RemoteIDModule/webinterface.cpp

In this PR, a pop up is shown if the OTA upgrade via the web interface fails. 
For instance if the wrong file is uploaded.

Provide a pop up if the OTA upgrade fails

---

RemoteIDModule/RemoteIDModule.ino

In the current implementation, the UAS data variable that contains the RID payload is only initialized during boot. Also when a "valid" var like SelfIDValid is set to 1, it will remain 1 until the RID module reboots.
In the PR, the UAS data variable is initialized before filling it.
So if a packet payload has no valid data anymore (like location, system, selfID etc), do not broadcast it anymore. Otherwise the old, outdated, data would be used, as in the current implementation.

init UAS payload in set_data

---

README.md
RemoteIDModule/Makefile
RemoteIDModule/board_config.h
RemoteIDModule/parameters.cpp

This PR add support for the db202mav module.

Add support for the Bluemark db202mav RemoteID module

---

RemoteIDModule/RemoteIDModule.ino
RemoteIDModule/parameters.cpp
RemoteIDModule/parameters.h
RemoteIDModule/transport.cpp

Added a define in option.h to disable all pre-arm checks (OVERRIDE_ARM_STATUS). Default disabled, it is useful for development purposes.

Override pre-arm checks

---

RemoteIDModule/BLE_TX.cpp
RemoteIDModule/RemoteIDModule.ino

The BT5. WLAN NaN and WLAN broadcast function use the odid_message_build_pack function of the opendrone ID lib to encode data.  That function uses the "valid" vars of each packet (basicID, location, system etc) to determine if it needs to be encoded. The BT4 transmission uses a slightly different approach, not using these  "valid" vars
In this PR:
- use the "valid" vars for BT4 transmission too (to have similar behavior for all transmission protocols)
- only set SelfID and operatorID packets to valid if data is entered.

Do not broadcast empty messages

---

RemoteIDModule/BLE_TX.cpp
RemoteIDModule/Makefile
RemoteIDModule/RemoteIDModule.ino

Minor bugfixes:
- do not require both python 2 and python 3 to upload the firmware. On my pc without calling python3 explicitly, python 2 was assumed in some places.
- Depending on whether Basic ID 2 was enabled, transmission rate for BT4 was wrong in some cases.
- For BT4, header length was not set initially so the advertiser was crashing when no messages were received, due to length being 0.

Bugfixes upstream

---

RemoteIDModule/DroneCAN.cpp
RemoteIDModule/mavlink.cpp
RemoteIDModule/transport.cpp

ArduRemoteID implementation for this PR https://github.com/ArduPilot/mavlink/pull/295

use latest mavlink definitions for MAV_ODID_ARM_STATUS

---

RemoteIDModule/DroneCAN.cpp
RemoteIDModule/parameters.cpp
RemoteIDModule/parameters.h

In [PR91](https://github.com/ArduPilot/ArduRemoteID/pull/91/files), the lock_level -1 was introduced. However, the parameter did not allow to set it to negative values, because it was defined as uint8_t.
This PR converts the lock_level to int8_t. 
Via DroneCAN GUI tool I can set it to -1. Via Mission Planner, it doesn't work. Not sure if something is missing in this PR or if it is a limitation of Mission Planner/MAVLink.

allow lock_level to set to -1

---

RemoteIDModule/parameters.cpp
RemoteIDModule/parameters.h

This PR adds the parameter TO_DEFAULTS. If set to 1, it will reset all values to their default value. And will also set the TO_DEFAULTS parameter to 0 again. 
This is useful for ArduRemoteID devices that don't have a droneCAN interface. These devices don't have the option to configure string parameters. Of course, a user could flash the firmware via a serial interface; this parameter is a better way without reflashing firmware.

parameter reset to defaults

---

RemoteIDModule/RemoteIDModule.ino
RemoteIDModule/parameters.h

In some scenario you don't want the ArduRemoteID device to store or use BasicID info from the parameters.
This PR adds the option OPTIONS_DONT_SAVE_BASIC_ID_TO_PARAMETERS to the options var. If set it won't use the basic ID info set  in the parameters nor will it save basicID info to parameters if nothing has been set.

Option to not use or save BasicID info to parameters

---

RemoteIDModule/CANDriver.cpp
RemoteIDModule/CANDriver.h
RemoteIDModule/DroneCAN.cpp

this allows the ESP32 to cope with high rate traffic for DroneCAN ESCs without choking. We use the priority field as a discriminator as the TWAI acceptance filters are don't allow complex enough filters to work on all the message IDs we need. We rely on the messages we want being low priority

DroneCAN: use TWAI acceptance filters

---

RemoteIDModule/RemoteIDModule.ino
RemoteIDModule/transport.cpp

In the current implementation, the check_parse fails on the **first** error whenit encounters bad data in one of the RID packets. 
In this PR, the function will collect all bad data errors and include the packets that fail in in the ARM status error field. This is useful in case the data stream has multiple errors. For instance if the system message has an error and the operator ID too, the current implementation would only return that the system message fails.

include multiple encoding errors in OPEN_DRONE_ID_ARM_STATUS message

---

RemoteIDModule/DroneCAN.cpp
RemoteIDModule/mavlink.cpp
RemoteIDModule/parameters.h

- existing code did only print a message on the serial console if a Remote ID message was received via DroneCAN. 
- this PR prints those messages for MAVLink too. And includes also the interface where the packet was received.

print received Remote ID messages on serial console for both MAVLink and DroneCAN

---

RemoteIDModule/CANDriver.cpp
RemoteIDModule/DroneCAN.cpp

don't get stuck in rx at very high packet rates

CAN: handle higher packet rate

---

.github/workflows/test_build.yml
scripts/install_build_env.sh

... now also clamps empy to a specific version so CI can pass.  Same version we use in ArduPilot.

.github: move upload-artifact to @v4 to get CI to pass

---

scripts/generate_keys.py
scripts/install_build_env.sh
scripts/secure_command.py
scripts/sign_fw.py

https://github.com/ArduPilot/ardupilot/pull/27095

Tools: specify pymonocypher version in more places

---

RemoteIDModule/RemoteIDModule.ino
RemoteIDModule/board_config.h
RemoteIDModule/parameters.cpp
RemoteIDModule/parameters.h

Support software configured termination.

add CAN_TERMINATE for software driven termination
