.gitmodules
RemoteIDModule/BLE_TX.cpp
RemoteIDModule/BLE_TX.h
RemoteIDModule/RemoteIDModule.ino
RemoteIDModule/WiFi_TX.cpp
RemoteIDModule/WiFi_TX.h
libraries/add_libraries.sh

added BT5 support

---

RemoteIDModule/RemoteIDModule.ino

now users can connect the dongle to SITL with the uart usb port

support dual serial

---

BUILDING.md
RemoteIDModule/Makefile

get rid of the dreaded arduino UI

switched to a Makefile

---

.gitignore
RemoteIDModule/BLE_TX.cpp
RemoteIDModule/DroneCAN.cpp
RemoteIDModule/DroneCAN.h
RemoteIDModule/RemoteIDModule.ino
RemoteIDModule/mavlink.cpp
RemoteIDModule/mavlink.h
RemoteIDModule/options.h

default to broadcast at startup

added build options in options.h

---

RemoteIDModule/BLE_TX.cpp
RemoteIDModule/mavlink.cpp

cleanup BLE advertising and mavlink debug

prevent serial error msgs corrupting mavlink

---

.github/workflows/test_build.yml
RemoteIDModule/BLE_TX.cpp
RemoteIDModule/CANDriver.cpp
RemoteIDModule/Makefile
RemoteIDModule/RemoteIDModule.ino
RemoteIDModule/board_config.h
RemoteIDModule/options.h

support building on BlueMark C3 board

---

RemoteIDModule/DroneCAN.cpp
RemoteIDModule/DroneCAN.h
RemoteIDModule/RemoteIDModule.ino
RemoteIDModule/mavlink.cpp
RemoteIDModule/mavlink.h
RemoteIDModule/mavlink_msgs.h
RemoteIDModule/transport.cpp
RemoteIDModule/transport.h

added transport abstraction

---

COPYING.txt
README.md
RemoteIDModule/RemoteIDModule.ino

this vendors the flexibility to use public keys for lockdown on consumer RemoteID modules, which may be required for FAA approval
buzz and Roel, I need your OK for this

relicense under GPLv2+

---

RemoteIDModule/Makefile
RemoteIDModule/RemoteIDModule.ino
RemoteIDModule/partitions.csv

ready for OTA update and parameters

new partition scheme

---

README.md
RemoteIDModule/RemoteIDModule.ino
RemoteIDModule/efuse.cpp
RemoteIDModule/efuse.h
RemoteIDModule/parameters.h

prevent firmware upload with USB or JTAG

setup efuses on LOCK_LEVEL=2

---

RemoteIDModule/status.cpp

Format the "Up Time" as h:mm:ss.
I make sure that the minute and second values do not move to the left or right.
AFTER
BEFORE

RemoteIDModule: Format update time as h:mm:ss

---

RemoteIDModule/DroneCAN.cpp
RemoteIDModule/RemoteIDModule.ino
RemoteIDModule/mavlink.cpp

if BasicID params not set but available from GCS then set the parameters

auto-update BasicID info from GCS

---

RemoteIDModule/status.cpp

Altitude of -1000 is UNKNOWN.
I want to show defined in TABLE 7 of F3411-22A.
AFTER
BEFORE

Altitude: Use Altitude encoding notation

---

scripts/secure_command.py

added --bus-num to secure_command.py

---

RemoteIDModule/RemoteIDModule.ino
RemoteIDModule/status.cpp
RemoteIDModule/web/index.html

fixed web server status web operator location is lost

---

scripts/secure_command.py

this allows for secure_command.py over support.ardupilot.org signed remote link

scripts: added mavlink signing key to secure_command.py

---

README.md
RemoteIDModule/DroneCAN.cpp
RemoteIDModule/Makefile
RemoteIDModule/RemoteIDModule.ino
RemoteIDModule/board_config.h
RemoteIDModule/led.cpp
RemoteIDModule/led.h
RemoteIDModule/mavlink.cpp
RemoteIDModule/parameters.cpp
RemoteIDModule/transport.cpp
RemoteIDModule/web/js/tools.js

This PR add support for the BlueMark db210pro board based on an ESP32-S3 chip.
It also reverted -for now- the ARM STATUS definitions as this issue describes: https://github.com/ArduPilot/ArduRemoteID/issues/114 Otherwise it won't compile.
I mean it compiles locally, apparently the automatic build is broken.

support for BlueMark db210pro module

---

RemoteIDModule/Makefile

ensure git hash in releases is correct

always update git hash on any build

---

README.md
RemoteIDModule/Makefile
RemoteIDModule/board_config.h
RemoteIDModule/parameters.cpp
RemoteIDModule/web/js/tools.js

This PR adds support for the db203can board.
Also it fixes the web interface (displaying the correct boardname etc) for the db202mav and the db203can

add support for db203can board

---

RemoteIDModule/DroneCAN.cpp
RemoteIDModule/mavlink.cpp

allow for param set with -ve lock level

fixed handling of negative lock level

---

README.md

Add Holybro Remote ID Module to README.md

Add Holybro Remote ID Module to README.md
